[gnome]
extensions = [
  # "AlphabeticalAppGrid@stuarthayhurst",
  # "tactile@lundal.io",
  "dash-to-dock@://gmail.com",
  "trayIconsReloaded@selfmade.pl",
  # "monitor@astraext.github.io",
  "vertical-workspaces@G-dH.github.com"
]

[gnome.settings]
"org.gnome.desktop.wm.preferences button-layout" = ":minimize,maximize,close"
"org.gnome.desktop.interface color-scheme" = "prefer-dark"
"org.gnome.desktop.interface gtk-theme" = "Dracula"
"org.gnome.desktop.wm.preferences theme" = "Dracula"
"org.gnome.desktop.interface icon-theme" = "Dracula"
"org.gnome.desktop.interface cursor-theme" = "Dracula-cursors"
"org.gnome.TextEditor style-scheme" = "dracula"

[gnome.shortcuts]
"Terminal" = { binding = "<Ctrl><Alt>t", command = "kitty" }
