[kde.shortcuts]
"kitty.desktop" = { binding = "Ctrl+Alt+T", group = "services" }
"org.kde.konsole.desktop" = { binding = "none", group = "services" }

[kde.theme]
"kwriteconfig:kdeglobals:General:ColorScheme" = "Dracula"
"kwriteconfig:kde-gtk-config:GTK:theme" = "Dracula"
"kwriteconfig:gtk-4.0:Settings:gtk-theme-name" = "Dracula"
"kwriteconfig:plasmarc:Theme:name" = "Dracula"
"kwriteconfig:kwinrc:org.kde.kdecoration2:theme" = "Dracula"
"kwriteconfig:kdeglobals:Icons:Theme" = "Dracula"
"kwriteconfig:kcminputrc:Mouse:cursorTheme" = "Dracula-cursors"
