[env]
DESKTOP = "gnome"

[bootstrap.packages]
"apt:gnome-shell-extensions" = "latest"
"apt:gnome-software-plugin-flatpak" = "latest"

[tasks."distro:setup:desktop"]
run = [
    { task = "distro:desktop:gnome:extensions" },
    { task = "distro:desktop:gnome:sets" },
    { task = "distro:desktop:gnome:shortcuts" },
]
