[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink-each"

[dotfiles]
"~/" = { source = "~/.dotfiles", mode = "symlink-each", exclude = [".git", ".gitignore", "README.md"] }
# VSCode OSS
"~/.vscode-oss" = { source = "~/.dotfiles/.vscode", mode = "symlink-each" }
"~/.config/Code - OSS/User/settings.json" = { source = "~/.dotfiles/.config/Code/User/settings.json", mode = "symlink" }

[bootstrap.repos]
# Programs
"~/.local/opt/reshade" = { url = "git@github.com:kevinlekiller/reshade-steam-proton.git" }

[tools]
go = "latest"
powershell = "latest"
python = "latest"
usage = "latest"
uv = "latest"
